### ISSUE TITLE
How do you register and then use a custom charts theme?

### ISSUE THREAD

**Issue by rszalski** [idea2app/ECharts-JSX#12]
Hi, thank you for working on this!

I was wondering if there is a way to first register (`echarts.registerTheme()`) and then use it with this library? I would like to use https://echarts.apache.org/en/theme-builder.html with this lib.

I was able to register the theme like so:

```
import { registerTheme } from 'echarts';

console.log(registerTheme);

registerTheme('my_theme', {
  backgroundColor: '#f4cccc',
});
```

But I'm not sure if this is robust given that this happens outside of any initialization of `echarts` that `echarts-jsx` does in the `ECharts` class.

Another issue I ran into is that I don't see a way to define what theme I'd like to use. I'd expect there to be a prop on e.g. `<CanvasCharts />` component. I found the `init` code in the `ECharts` class but no theme is being passed as the second argument. I also don't think I could patch the package to workaround this, as it is distributed as compiled mjs/umd source.

What would be the best way to achieve that?

**Comment by TechQuery** [comment]
@rszalski Thanks for your suggestion! You can try this enhancement in https://github.com/idea2app/ECharts-JSX/releases/tag/v0.5.4

**Comment by rszalski** [comment]
Really delayed, but I wanted to say that I tested it and it works. Thanks!
